// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBdillZi6ycw5q2ogcFMPNZp-QSM5Q4l8',
    appId: '1:261190461441:web:3c201f3f381aa4ae8a3800',
    messagingSenderId: '261190461441',
    projectId: 'monster-ranker-app',
    authDomain: 'monster-ranker-app.firebaseapp.com',
    databaseURL: 'https://monster-ranker-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monster-ranker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgwclotqJWQTWXblmZVxqW4K8sqkxvCN8',
    appId: '1:261190461441:android:674ba9783c17d1cb8a3800',
    messagingSenderId: '261190461441',
    projectId: 'monster-ranker-app',
    databaseURL: 'https://monster-ranker-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monster-ranker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Dpnnl9zmdTsvgCiWdTktz8YTfKeV4yI',
    appId: '1:261190461441:ios:73e562cecd9344228a3800',
    messagingSenderId: '261190461441',
    projectId: 'monster-ranker-app',
    databaseURL: 'https://monster-ranker-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monster-ranker-app.appspot.com',
    iosBundleId: 'com.example.navbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Dpnnl9zmdTsvgCiWdTktz8YTfKeV4yI',
    appId: '1:261190461441:ios:ea53b6836bb7f1b28a3800',
    messagingSenderId: '261190461441',
    projectId: 'monster-ranker-app',
    databaseURL: 'https://monster-ranker-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monster-ranker-app.appspot.com',
    iosBundleId: 'com.example.navbar.RunnerTests',
  );
}
